### ISSUE TITLE
Error 413 while upoading file

### ISSUE THREAD

**Issue by Bertrand134** [YunoHost-Apps/grist_ynh#12]
Hello,

I've installed grist on my yuno. Before I had installed it on a docker.
The install was perfect and everything go well.
But when I want to upload a file  named *.grist. I receive an error : "Upload failed:413"

that is not for all files.
![image](https://github.com/YunoHost-Apps/grist_ynh/assets/80748449/1c8492e2-c509-425b-bef7-66b2217a7738)

I didn't found any log.
Maybe it's something with the size of the file?
because I managed to upload files less than 1Mo but not bigger one (I cannot with one which is 1,3Mo.

I'm waiting if you have question.
Bertrand
I

**Comment by fflorent** [comment]
Hello and thanks for the report

> I didn't found any log.

You can find logs through the command line: `sudo journalctl -f -u grist`.

>  Maybe it's something with the size of the file?

Yes it is, the nginx configuration should be patched to allow more than 1Mb.

**Comment by Bertrand134** [comment]
Thank you for your return

Here is the log:
Dec 04 16:25:46 yuno.XXX.fr run.sh[1369182]: 2023-12-04 16:25:46.797 - warn: client error fileName=https://grist.XXX.fr/v/unknown/main.bundle.js, lineNumber=2, columnNumber=125007, message=Upload failed: 413, name=UserError, docId=undefined, page=https://gristXXXX.fr/o/docs/, language=fr, platform=Win32, userAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0, org=docs, email=bertrand@yuno.xxxx.fr, userId=5, altSessionId=ar3dVmj2rLMTAv9gsfczEr

I search in the nginx conf.

**Comment by fflorent** [comment]
I think that it should be fixed in the testing branch. If you want to go ahead and try (feedback welcome :pray:):
```
yunohost app upgrade grist -u https://github.com/YunoHost-Apps/grist_ynh/tree/testing --force
```

Ensure to keep a backup of your grist beforehand (a backup is created before the upgrade, either copy it elsewhere or create a manual backup…).

**Comment by Bertrand134** [comment]
I tried the testing branch and everything went ok.
I managed to import a file bigger than 5Mo.

Thank you Florent,

**Comment by fflorent** [comment]
The fix is integrated, thanks for the feedback!
