### ISSUE TITLE
Unable to INSTALL grist (standard or testing branch) BUT able to RESTORE backup

### ISSUE THREAD

**Issue by mo-kuh** [YunoHost-Apps/grist_ynh#20]
### Describe the bug

- Grist install fails half way through. Kinda is installed, kind of not. 
- It starts but doesn't finish. No errors shown. Stops "in the middle"
- it is available in the user interface, shows up under "Applications" admin interface
- BUT: nginx conf file is NOT created and grist is NOT reachable
* Grist continues to be "busy" in the background (checked with "TOP" command in cli)
* Log stops (gets stuck) with this line: "DEBUG - + webpack --config buildtools/webpack.config.js --mode production"
* Using the testing branch did NOT help :(

### Context

- Hardware: VPS bought online (Debian11)
- YunoHost version: 11.2.9.1
- I have access to my server: Through SSH | through the webadmin |
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: 

### Steps to reproduce

- I tried to install Grist (from cli and web interface) both the standard and testing branch (normal and debug install)
- On 2 servers the install fails, on 1 smaller yunohost instance (with less apps installed) the install is successfull

### Expected behavior

- Grist installs, is available in the user interface, shows up under "Applications" admin interface, nginx conf file is created and grist is reachable

### Logs

* https://paste.yunohost.org/raw/enoquhulex
* Log stops (gets stuck) with this line: "DEBUG - + webpack --config buildtools/webpack.config.js --mode production"

### Solution (work around)
- I tried to install grist several times. I couldnt identify the conflict. 
- I assume there is a conflict between grist and another app (Its not a port problem. Port 8484 is free / unsed / open). 
  - I could install grist on a similar setup (difference: less applications installed)
  - Thats why i assume the problem is a conflict between installed apps and the to be install grist app

I am happy that I found a work around: 

- INSTALL grist in a small environment
  - Add the same domain on the "install" environment as on the target (destination) environment  (example: "grist.domain.org")
  - Install grist app on the domain (example: "grist.domain.org")
- BACKUP grist on the "install" environment
   - Howto backup: https://yunohost.org/en/backup)
   - Download grist backup file (example: "somenumber.tar")
- RESTORE grist on the "target" environment 
  - Add the domain on the "target" environment 
  - Howto: https://yunohost.org/en/backup
    - Upload the grist backup to the target environment
    -  Go to "BACKUP Restore grist on the "target" environment
- ENJOY your installed and working grist app: "grist.domain.org"

**Comment by fflorent** [comment]
@mo-kuh Thanks for your report. 
Indeed, I am interested in getting more information on the capacities of your VPS (especially the amount of RAM and CPU). 

I also see that the installation was probably interrupted manually after 10 minutes of build:
> 2024-01-16 00:33:50,181: DEBUG - + webpack --config buildtools/webpack.config.js --mode production
> 2024-01-16 00:44:54,716: ERROR - Unable to install grist: The operation was manually interrupted?

 The build can take long, as suggested @orhtej2, please try again, with patience it should probably work.

**Comment by mo-kuh** [comment]
Hello,

thank you for giving feedback so fast.

1) Manual interrupt
Yes, i did manually abort the install after some time. But before this I waited.

2) Technical details
Sorry for not providing the server (environment) details in the first place. I understand that the install can take a long time. I actually waited alot and the install never "finished". The servers (1+2) where busy or even unresponsive while waiting. At some point the server where responsive again without the install being finished. I am happy to try the "install over night" again BUT please note: The install worked and was VERY fast on the "smaller" (lowest performance) server 3.

Server1 (VPS): https://www.ionos.de/server/vps
* IONOS VPS L
* 4 Core CPU
* 8GB RAM
* 240 GB SSD

Server2 (Local machine): https://geizhals.de/lenovo-thinkcentre-m710q-tiny-10mr000xge-a1612550.html
* Lenovo ThinkCentre M710q Tiny, Core i5-7400T (10MR000XGE) 
* 4 Core CPU (2.40-3.00GHz)
* 16GB RAM
* 256GB SSD

Server3 (VPS): https://www.ionos.de/server/vps
* IONOS VPS M
* 2 Core CPU
* 4GB RAM
* 160 GB SSD


Anyway: I will try again and report back. Thanks :)

**Comment by mo-kuh** [comment]
Install is working. I tested it on both server (1+2). I just had to wait longer. It never took so long so install an app. Sorry for my impatience.
 
Still, I hope my original post is helpful for someone.

Thanks alot for bringing grist to yunohost!

**Comment by fflorent** [comment]
I am very happy that you could manage to install Grist!
Thanks for your feedback :)
