### ISSUE TITLE
How to configure environment variables?

### ISSUE THREAD

**Issue by jlnbdt** [YunoHost-Apps/grist_ynh#60]
Hi,

I’m trying to use webhooks with my own instance of n8n but I get `Incomplete | Provided url is forbidden`. I’ve read that I’ve to configure the variable `ALLOWED_WEBHOOK_DOMAINS`.

So,
1. I’ve made a copy of `default.env `to `custom.env`
2. I Add a line `ALLOWED_WEBHOOK_DOMAINS=https://n8n_domain.tld` into `custom.env`
3. I restart Grist service with `yunohost service restart grist`

But I always get the same error message. What did I miss?

Thanks a lot!

**Comment by fflorent** [comment]
Hi @jlnbdt 

Hello,

> I’ve made a copy of default.env to custom.env

You don't have to. The `custom.env` file should already exist in `__DATA_DIR__/custom.env`. Usually `__DATA_DIR__` can be replaced by `/home/yunohost.app/grist` (so it would usually be located at `/home/yunohost.app/grist/custom.env`).

Any variable that exists there will complement those in `default.env`. Just add the variables you need in `custom.env`.

> But I always get the same error message. What did I miss?

In a shell, run:
```
sudo yunohost app shell grist
```

Then:
```
echo $ALLOWED_WEBHOOK_DOMAINS
```

Is the value you assigned to your variable is printed?

**Comment by jlnbdt** [comment]
Hi,

Thank you for your quick reply.

> You don't have to. The custom.env file should already exist in __DATA_DIR__/custom.env. Usually __DATA_DIR__ can be replaced by /home/yunohost.app/grist (so it would usually be located at /home/yunohost.app/grist/custom.env).
> Any variable that exists there will complement those in default.env. Just add the variables you need in custom.env.

Yes indeed, I understood that afterwards!

> Is the value you assigned to your variable is printed?

Yes it is.

But I think I've found my mistake: I have not to write "https://" 🙄

**Comment by fflorent** [comment]
> But I think I've found my mistake: I have not to write "https://" 🙄

True, it only works with domains.
